"""HOW to intervene.

An Intervener consults the target (large) model about the small model's current
reasoning trace and returns an edit to apply. This is separate from WHEN to
intervene (triggers.py). Add a new mechanism = new Intervener subclass + a line in
make_intervener; nothing else changes.

The only intervener implemented is `mentor`: it asks the target model to either
return `<NO_EDIT>` (leave the trace alone) or a concise `<MENTOR_REPAIR>...</...>`
note that gets appended to the small model's thinking so it self-corrects.
`--repair-thinking` toggles whether the target model reasons before answering.
"""

from __future__ import annotations

from dataclasses import dataclass

from common import ModelClient, Usage, split_think


# --------------------------------------------------------------------------------------
# Intervention result: what to do to the small model's trace.
# --------------------------------------------------------------------------------------
@dataclass
class Intervention:
    action: str          # "none" | "append" | "replace"
    text: str = ""       # the parsed edit applied to the trace ("" for none)
    raw: str = ""        # the large model's full raw response for this consultation


# --------------------------------------------------------------------------------------
# Mentor intervener (the prompt is exactly as specified; edit here to tune it).
# --------------------------------------------------------------------------------------
MENTOR_PROMPT = """You are an expert in reparing reasoning traces of LLMs. For the given mathematical task, a particular reasoning trace was generated by a possibly 'weaker' model.  The trace is intermediate and is thus likely not complete. Your job is to think carefully about whether the trace contains a concrete mathematical or logical error, or is using the wrong approach, or is going in the wrong direction, or any other issue compared to what you would have done. Based on that, you either output a single word '<NO_EDIT>' as your final answer, if you feel the trace is fine, or if the trace has too little information to make a reasonable judgement about its correctness. Other you should output a concise repair statement  within <MENTOR_REPAIR> tags, that when appended to the LLM whose trace you are judging, the LLM will come to the right track and correct whatever it was doing wrong. Make sure not to use any more words in your repair statement than is necessary for this purpose.

Rules:
- Do not solve the problem from scratch.
- Do not reveal or compute the final answer.
- Do not improve style or add alternative methods.
- Choose <MENTOR_REPAIR> only if there is a clear local error or misguided reasoning that is likely to affect the final answer.
- If the reasoning is incomplete but not wrong, output <NO_EDIT/>.

INPUT: {input_question}

LLM REASONING TRACE: {reasoning_trace}

OUTPUT: {<NO_EDIT> or <MENTOR_REPAIR>repair statement<\\MENTOR_REPAIR>}
"""

_OPEN_TAG = "<MENTOR_REPAIR>"
_CLOSE_TAGS = ("</MENTOR_REPAIR>", "<\\MENTOR_REPAIR>", "<MENTOR_REPAIR/>")


class Intervener:
    def intervene(self, example, thought: str, large: ModelClient,
                  cfg, usage: Usage) -> Intervention:
        raise NotImplementedError


class MentorIntervener(Intervener):
    def intervene(self, example, thought, large, cfg, usage) -> Intervention:
        # str.replace (not .format): the prompt contains literal { } braces.
        content = (MENTOR_PROMPT
                   .replace("{input_question}", example.user_prompt)
                   .replace("{reasoning_trace}", thought))
        prompt = large.build_prompt(content, system=None,
                                    enable_thinking=cfg.repair_thinking)
        res = large.complete(prompt, max_tokens=cfg.repair_max_tokens,
                             temperature=cfg.temperature, top_p=cfg.top_p,
                             top_k=cfg.top_k, seed=cfg.seed)
        usage.add(res.prompt_tokens, res.completion_tokens, res.seconds, res.prompt_ids, res.gen_ids)
        rep = _parse_repair(res.text)
        if rep is None:
            return Intervention("none", raw=res.text)
        return Intervention("append", rep, raw=res.text)


def _parse_repair(raw: str) -> str | None:
    """Return the repair statement, or None for <NO_EDIT> / unparseable output.

    Drops the target model's own <think> block first, then extracts the text
    between <MENTOR_REPAIR> and its closing tag (tolerating a missing close tag).
    """
    _, after_think = split_think(raw)
    text = after_think if after_think.strip() else raw
    if _OPEN_TAG not in text:
        return None                       # <NO_EDIT> or anything without a repair
    body = text.split(_OPEN_TAG, 1)[1]
    for close in _CLOSE_TAGS:
        if close in body:
            body = body.split(close, 1)[0]
            break
    body = body.strip()
    return body or None


INTERVENERS = ["mentor"]


def make_intervener(name: str) -> Intervener:
    if name == "mentor":
        return MentorIntervener()
    raise ValueError(f"unknown intervener '{name}'. options: {INTERVENERS}")
